apiVersion: v1
kind: Pod
metadata:
  name: kspacey
  labels:
    argoproj.io/vertex: "true"
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: swilliams
  labels:
    argoproj.io/vertex: "true"
  annotations:
    argoproj.io/edges: "///kspacey"
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: bpitt
  labels:
    argoproj.io/vertex: "true"
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: hford
  labels:
    argoproj.io/vertex: "true"
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lwilson
  labels:
    argoproj.io/vertex: "true"
  annotations:
    argoproj.io/edges: "//pods/hford"
---
apiVersion: v1
kind: Pod
metadata:
  name: kbacon
  labels:
    argoproj.io/vertex: "true"
  annotations:
    argoproj.io/edges: "///swilliams,///bpitt,//configmaps/lwilson"
spec:
  containers:
    - name: main
      image: cowsay:v1