apiVersion: v1
kind: Pod
metadata:
  name: kspacey
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/vertex-label: Kevin Spacey
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: swilliams
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/edges: "///kspacey"
    graph.argoproj.io/vertex-label: Saul Williams
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: bpitt
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/vertex-label: Brad Pitt
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: hford
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/vertex-label: Harrison Ford
spec:
  containers:
    - name: main
      image: cowsay:v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lwilson
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/edges: "//pods/hford"
    graph.argoproj.io/vertex-label: Luke Wilson
---
apiVersion: v1
kind: Pod
metadata:
  name: kbacon
  labels:
    graph.argoproj.io/vertex: "true"
  annotations:
    graph.argoproj.io/edges: "///swilliams,///bpitt,//configmaps/lwilson"
    graph.argoproj.io/vertex-label: Kevin Bacon
spec:
  containers:
    - name: main
      image: cowsay:v1